### ISSUE TITLE
ROS2 package cannot find the libraries at runtime

### ISSUE THREAD

**Issue by pgupta2050** [ICube-Robotics/acados_vendor_ros2#27]
I have built this package in my workspace and I am using it as a dependency in my ROS2 package to run the OCP. My ROS2 package is here: https://github.com/pgupta2050/rzr_mpcrl  

My system: 
```
Linux cra-terra-u22 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

I get the following error at run time from I run ` ros2 run rzr_mpcrl dlc_mpc.py`

```
Warning: Please note that the following versions of CasADi are officially supported: 3.4.03.4.5 or 3.5.1 or 3.5.2 or 3.5.3 or 3.5.4 or 3.5.6 or 3.5.5 or 3.6.0 or 3.6.1 or 3.6.2 or 3.6.3 or 3.6.4.
 If there is an incompatibility with the CasADi generated code, please consider changing your CasADi version.
Version 3.6.5 currently in use.
rm -f libacados_ocp_solver_bicycle_ode.so
rm -f acados_solver_bicycle_ode.o
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/acados -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/blasfeo/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/hpipm/include -I /home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/qpOASES_e/  -c -o acados_solver_bicycle_ode.o acados_solver_bicycle_ode.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/acados -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/blasfeo/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/hpipm/include -I /home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/qpOASES_e/  -c -o bicycle_ode_model/bicycle_ode_impl_dae_fun.o bicycle_ode_model/bicycle_ode_impl_dae_fun.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/acados -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/blasfeo/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/hpipm/include -I /home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/qpOASES_e/  -c -o bicycle_ode_model/bicycle_ode_impl_dae_fun_jac_x_xdot_z.o bicycle_ode_model/bicycle_ode_impl_dae_fun_jac_x_xdot_z.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/acados -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/blasfeo/include -I/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/hpipm/include -I /home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/include/qpOASES_e/  -c -o bicycle_ode_model/bicycle_ode_impl_dae_jac_x_xdot_u_z.o bicycle_ode_model/bicycle_ode_impl_dae_jac_x_xdot_u_z.c
cc -shared acados_solver_bicycle_ode.o bicycle_ode_model/bicycle_ode_impl_dae_fun.o bicycle_ode_model/bicycle_ode_impl_dae_fun_jac_x_xdot_z.o bicycle_ode_model/bicycle_ode_impl_dae_jac_x_xdot_u_z.o -o libacados_ocp_solver_bicycle_ode.so -L/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/lib -lacados -lhpipm -lblasfeo -lm -lqpOASES_e \
-L -l
/usr/bin/ld: cannot find -lqpOASES_e: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:124: ocp_shared_lib] Error 1
acados was compiled without OpenMP.
Traceback (most recent call last):
  File "/home/cra/ros2_ws/install/rzr/lib/rzr/dlc_mpc.py", line 241, in <module>
    closed_loop_simulation()
  File "/home/cra/ros2_ws/install/rzr/lib/rzr/dlc_mpc.py", line 42, in closed_loop_simulation
    acados_ocp_solver = AcadosOcpSolver(
  File "/home/cra/ros2_ws/install/acados_vendor_ros2/local/lib/python3.10/dist-packages/acados_template/acados_ocp_solver.py", line 249, in __init__
    self.shared_lib = DllLoader(self.shared_lib_name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/cra/ros2_ws/src/rzr/scripts/c_generated_code/libacados_ocp_solver_bicycle_ode.so: cannot open shared object file: No such file or directory
[ros2run]: Process exited with failure 1

```

Not sure what the issue is, and why it is looking in the wrong path or no path. 
I do have acados python interface built on my system and added that path to the LD_LIBRARY_PATH. These are my env variables:
```
acados_lib_path=/home/cra/acados/interfaces
acados_include_path=/home/cra/acados/include
AMENT_PREFIX_PATH=/home/cra/ros2_ws/install/ds_autonomy_sim_demo:/home/cra/ros2_ws/install/rzr_mpcrl:/home/cra/ros2_ws/install/rzr_mpcrl_interfaces:/home/cra/ros2_ws/install/rzr:/home/cra/ros2_ws/install/acados_vendor_ros2:/opt/ros/humble
CMAKE_PREFIX_PATH=/home/cra/ros2_ws/install/ds_autonomy_sim_demo:/home/cra/ros2_ws/install/rzr_mpcrl_interfaces:/home/cra/ros2_ws/install/rzr:/home/cra/ros2_ws/install/acados_vendor_ros2
ACADOS_PYTHON_INTERFACE_PATH=/home/cra/ros2_ws/install/acados_vendor_ros2/local/lib/python3.10/dist-packages/acados_template
PYTHONPATH=/home/cra/ros2_ws/build/rzr_mpcrl:/home/cra/ros2_ws/install/acados_vendor_ros2/local/lib/python3.10/dist-packages:/home/cra/ros2_ws/install/rzr_mpcrl/lib/python3.10/site-packages:/home/cra/ros2_ws/install/rzr_mpcrl_interfaces/local/lib/python3.10/dist-packages:/opt/ros/humble/lib/python3.10/site-packages:/opt/ros/humble/local/lib/python3.10/dist-packages
LD_LIBRARY_PATH=/home/cra/ros2_ws/install/rzr/lib:/home/cra/ros2_ws/install/rzr_mpcrl_interfaces/lib:/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/lib:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/humble/opt/rviz_ogre_vendor/lib:/opt/ros/humble/lib/x86_64-linux-gnu:/opt/ros/humble/lib::/home/cra/acados/lib:~/acados/lib
ACADOS_SOURCE_DIR=/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2
PATH=/home/cra/ros2_ws/install/acados_vendor_ros2/opt/acados_vendor_ros2/bin:/opt/ros/humble/bin:/home/cra/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
```

Does anyone have any suggestions? It is not able to find the `libqpOASES_e.so`. Am I using your package wrong?

Thanks
Prakhar

**Comment by pgupta2050** [comment]
I am sorry, I was pulling something other than the master barnch, based on the instructions here: https://github.com/ICube-Robotics/acados_solver_ros2_examples/blob/c7031789c97d4bca1f08c50b76bf2c86dacc15f3/acados_solver_ros2_examples.repos#L4

One I pull the master branch and switch on the correct solver libraries to build with in the CMakeLists.txt file, it is able to find them ok.

Closing this issue.
